package pipeless-wasm:hooks;

interface types {
  variant user-data {
    empty,
    integer(s64),
    float(f64),
    str(string),
    // array(list<user-data>),
    // dictionary(tuple<string, user-data>),
  }

  record wasm-rgb-frame {
    uuid: string,
    original: list<list<list<u8>>>,
    modified: list<list<list<u8>>>,
    width: u32,
    height: u32,
    pts: u64,
    dts: u64,
    duration: u64,
    fps: u8,
    input-ts: float64,
    inference-input: list<list<list<f32>>>,
    inference-output: list<list<list<f32>>>,
    pipeline-id: string,
    frame-number: u64
    // user_data: UserData,
  }

//  record context {
//    to-change: string,
//  }
}

interface hook-interface {
  use types.{wasm-rgb-frame};
  hook: func(f: wasm-rgb-frame) -> wasm-rgb-frame;
}

world hook-component {
    //use types.{rgb-frame, context};
    //export hook: func(f: wasm-rgb-frame, c: context) -> wasm-rgb-frame;

    use types.{wasm-rgb-frame};
    export hook-interface;
}
